version: '{build}'
install:
- git submodule update --init --recursive
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- build.cmd Default
test: off
artifacts:
- path: bin/Arachne.*.nupkg
  name: nuget
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/483150f6f9c28934e89b
